### ISSUE TITLE
Error when compiling BlackBone source

### ISSUE THREAD

**Issue by fnielson1** [ergrelet/dll-hot-reload#3]
When I try to compile the blackbone solution, I get this error:

```
error C2275: 'blackbone::_UNICODE_STRING_T<uint64_t>::type': expected an expression instead of a type
...
ot-reload-main\build\build\_deps\blackbone-src\src\BlackBone\BlackBone.vcxproj]
          with
          [
              _T1=blackbone::_UNICODE_STRING64
          ]```
		  
		  
I'm on Windows 10 with Visual Studio Community 2022

**Comment by ba0f3** [comment]
On VS 2022, disable standards conformance with `/permissive` flag by go to BlackBone project's Properties -> Configuration Properties -> C/C++ -> Conformance mode => **No (/permissive)**

**Comment by fnielson1** [comment]
Thank you! Worked like a charm!

**Comment by ergrelet** [comment]
Hi! 
Thanks for the report, it seems permissive mode is indeed required on recent VS 2022 versions. I've pushed a fix on `main`!
